FROM alpine:latest

RUN apk add --no-cache bash vim

RUN apk add --no-cache make gcc g++ python git nodejs nodejs-npm yarn \
	&& rm -rf /var/lib/apt/lists/* \
    /var/cache/apk/* \
    /usr/share/man \
    /tmp/*


# Bundle src source
COPY . /app
WORKDIR /app
RUN npm install -g npm
RUN npm install
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]
